### ISSUE TITLE
How to set a specific prefix for the password?

### ISSUE THREAD

**Issue by spidgorny** [bes/KeystoreBrute#2]
I know the beginning of the password and I tried to start the process from the middle as if it went until the moment when the current `this.counts` is corresponding to the prefix.

I've tried to initialize `this.counts` in `PasswordGenerator#start` method. But my changes are ignored. Where should I inject my password prefix?

**Comment by bes** [comment]
I'd say a quick hack would be to put your prefix on line 176 https://github.com/bes/KeystoreBrute/blob/master/src/se/bes/br/Breaker.java#L176

Something like
```diff
+    passwd = "myPrefix" + mGenerator.getNextPassword();
-    passwd = mGenerator.getNextPassword();
```

And then start the process by giving a suitable startDepth, something like if you expect you password to be at least 10 characters then you would give `10 - "myPrefix".length()` i.e. `2`.

If you can write the whole thing as a generic command line argument to BruteMain, then you are welcome to do a PR.

**Comment by spidgorny** [comment]
Thank you!

    passwd = ("myPrefix" + new String(mGenerator.getNextPassword())).toCharArray();

Works.

**Comment by spidgorny** [comment]
BTW, why `char[]` and not `String`?
And why inner classes? Is this typical in Java?

**Comment by bes** [comment]
`char[]` because that's what `java.security.KeyStore` expects. Inner classes are very common in Java. This code was written by me 7 years ago, so it can probably be improved a lot, though.

Did you manage to open the keystore?

**Comment by spidgorny** [comment]
Not yet.
