### ISSUE TITLE
Generate keystore

### ISSUE THREAD

**Issue by Alireza-Razavi** [bes/KeystoreBrute#3]
Hi!
Is there any way to make a keystore over the apk file??
How to bruteforce the signature without existing the keystore file ?

**Comment by bes** [comment]
Brute forcing a cryptographic signature is often quite difficult and time consuming, by design.

This repository does not cover that use case. This repository can only brute force the password for an existing JKS.

**Comment by 11btux** [comment]
> Hi!
> Is there any way to make a keystore over the apk file??
> How to bruteforce the signature without existing the keystore file ?
>
